# Generated by Django 3.0.8 on 2020-08-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200829_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='description',
            new_name='bio',
        ),
    ]
