# Generated by Django 3.0.8 on 2020-08-29 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0003_auto_20200822_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='EchoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='echo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_projects', to='echo.EchoCategory'),
        ),
    ]
